### ISSUE TITLE
Invalid Mockito dependency scope

### ISSUE THREAD

**Issue by skyghis** [quux00/simplecsv#14]
Hi,

In version 2.0 the `mockito` dependency scope is not set. So when I include `simplecsv` on my dependencies I got a dependency to `mockito` :/

This dependency seam to be a test only dependency. Is it possible to add `<scope>test</scope>` for next version ?

Thanks in advance.

**Comment by quux00** [comment]
Yes, good catch.  Apologies for that oversight.  I will push out a new version this weekend.

**Comment by quux00** [comment]
A new version of simplecsv that corrects this issue is now available in maven central: https://search.maven.org/#artifactdetails|net.quux00.simplecsv|simplecsv|2.1|jar

**Comment by skyghis** [comment]
I confirm the fix. Thanks !
